from pydantic import BaseModel, Field

class AskRequest(BaseModel):
    query: str = Field(
        ...,
        description="User question to query the local document knowledge base",
        min_length=3
    )

class AskResponse(BaseModel):
    answer: str = Field(
        ...,
        description="Final answer generated by the agentic RAG pipeline"
    )
    latency: float = Field(
        ...,
        description="Time taken (in seconds) to generate the answer"
    )